### ISSUE TITLE
Remove hard-coded auth key from config.js

### ISSUE THREAD

**Issue by robconery** [Microsoft/TailwindTraders-Backend#4]
The AuthKey for Cosmos DB is hard-coded here, in case the `ENV` isn't set:

https://github.com/Microsoft/TailwindTraders-Backend/blob/8ed810773d937989a027f3ec1ba64f2d0ac092ec/Source/Services/Tailwind.Traders.Cart.Api/config.js#L8

This goes against our guidelines internally and externally. I would suggest relying explicitly on `process.env` or throwing.

**Comment by eiximenis** [comment]
Hi!
This is the authkey used by the CosmosDB emulator (on Windows).
The assumption (should be docummented) here is that if `AUTHKEY` is not set is because you are using CosmosDb emulator.

Need to document how to develop on local machine using CosmosDb emulator and Docker or Visual Studio, because is not a easy setup.

Thanks! :)

**Comment by robconery** [comment]
Understood. I would still suggest removing as AuthKeys, no matter what they're for, should not be hard-coded.

**Comment by eiximenis** [comment]
You're true on this.

Just pointing that, at least, this hardcoded key is not a _security_ issue. But it can be easily handled through `.env` file on Backend site.

I'll keep this issue open until this is fixed!

**Comment by eiximenis** [comment]
Hi @robconery 
I've updated the code and added documentation about how to configure containers for running locally.

**Comment by dasanagu** [comment]
Fixed with commit [d9bbee](https://github.com/Microsoft/TailwindTraders-Backend/commit/d9bbee343dd04ff9776964b0a0f583ad846b0dad)
