### ISSUE TITLE
Carts are open to anyone with an email

### ISSUE THREAD

**Issue by robconery** [microsoft/TailwindTraders-Backend#5]
If I understand this code correctly, any user with an email address can see what's in a given cart simply by adding an email address to a querystring:

https://github.com/Microsoft/TailwindTraders-Backend/blob/8ed810773d937989a027f3ec1ba64f2d0ac092ec/Source/Services/Tailwind.Traders.Cart.Api/routes/cartController.js#L14

This has a number of security ramifications. I would suggest using some type of non-discoverable key (like a GUID) or perhaps using anonymous auth with a JWT.

**Comment by eiximenis** [comment]
Yes,
This is related to the fake auth, wich currently we have. We are using email as "security token" because we don't have a token provider.
Currently `Authorization` header has the form  `Email foo@bar.baz` and that makes calls in behalf of `foo@bar.baz` user.
So **as a security point of view** you should consider that everything is open.

In the roadmap we have plans to use JWT with a custom provider (for "fake auth") and maybe with a real provider (like AADB2C).

Thx again!
