### ISSUE TITLE
Error: unknown shorthand flag: 'e' in -encodedCommand

### ISSUE THREAD

**Issue by isaacrlevin** [microsoft/TailwindTraders-Backend#76]
When attempting to deploy the Backend to AKS, I get this error when running `Deploy-Images-Aks.ps1`

> helm upgrade --install tailwindtraders-product products-api -f ..\helm\__values\gvalues.yaml --set ingress.hosts='{17a70b5634ff444a996f.westus2.aksapp.io}' --set image.repository=ttacrdwcdmtkxdlw3u.azurecr.io/product.api --set image.tag=latest --set hpa.activated=False

> Error: unknown shorthand flag: 'e' in -encodedCommand

I am running Helm 2.1.16 and Docker v19.03.5. Is there a gap in supported versions?

**Comment by OriolBonjoch** [comment]
Hi,

There was a problem with `Deploy-Images-Aks.ps1` script fixed in #77 pull request. Its not your case as its related to the Dns set but the message was the same. Could you run the helm script in a cmd prompt instead of a powershell? This will print the actual error.

Regarding the Helm versions I tried with v2.12.1. I don't know if the helm version is the cause but its a really old version compared with the one we used.

Thanks for reporting the issue.

**Comment by isaacrlevin** [comment]
running in CMD fixed the issue
